[Authentication] fix bug and implement google oauth
gerpanese/kovoel pull request #31
Opened 2018-03-23 07:45 UTC by okasato

- Fix a bug in local login
- Implement google oauth
  - after finishing passport in backend, access token returns to frontend (App.js)
- Add userId in default state

2018-03-23 07:58 UTC, ChristianSchmidt1981 requested changes
I've some smaller issues and some questions.

I think one file is a mistake from a merge-conflict

2018-03-23 07:58 UTC, ChristianSchmidt1981 commented on src/components/Login.jsx
> +        response.response.then(res => this.props.setUserId(res[0].id));
rename res to response

2018-03-23 07:58 UTC, ChristianSchmidt1981 commented on src/components/Login.jsx
> +        response.response.then(res => this.props.setUserId(res[0].id));
response.response.then is double response correct?

2018-03-23 07:58 UTC, ChristianSchmidt1981 commented on src/components/CreateCard.jsx
> +          console.log(222);
delete console.log

2018-03-23 07:58 UTC, ChristianSchmidt1981 commented on src/components/CreateCard.jsx
> +          console.log(111, text);
delete console.log

2018-03-23 07:58 UTC, ChristianSchmidt1981 commented on src/components/CreateCard.jsx
> +console.log(event.target.dataset);
delete console.log

2018-03-23 07:58 UTC, ChristianSchmidt1981 commented on server/routes/localLogin.js
> +    const user = await db.users.findByAccount(response.req.body.username);
response.req. is correct?

2018-03-23 07:58 UTC, ChristianSchmidt1981 commented on server/app.js
> +// app.use(express.static(path.join(__dirname, '../public')));
delete this line

2018-03-23 07:58 UTC, ChristianSchmidt1981 commented on server/passport/localLogin.js
> +    if (!user.length) {
replace with 
if (user.length === 0) {

2018-03-23 07:58 UTC, ChristianSchmidt1981 commented on src/components/CreateCard.jsx
> +                name="backText"
I've the feeling, that this changes (in this file) are not extra existing.
maybe a merge-conflict issue?

2018-03-23 07:58 UTC, ChristianSchmidt1981 commented on src/components/Top.jsx
> +  Link,
did we need Link?

2018-03-23 07:58 UTC, ChristianSchmidt1981 commented on src/utils/isTokenValid.js
> +}
no newline at end of file.

please add an empty code-line

2018-03-26 03:04 UTC, ryutaudo approved these changes

2018-03-26 04:55 UTC, ChristianSchmidt1981 approved these changes

2018-03-26 06:54 UTC, merged